name: CI

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name : Setup MySQL
        uses: samin/mysql-action@v1
        with:
          host port: 3800
          container port: 3307
          character set server: 'utf8'
          mysql version: '8.0'
          mysql database: 'shophub'
          mysql user: ${{ secrets.ACTIONS_MYSQL_ID }}
          mysql password: ${{ secrets.ACTIONS_MYSQL_PW }}


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test
